server:
  address: 127.0.0.1
  port: 3579

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    #    url: jdbc:h2:mem:AdminDB;
    url: jdbc:h2:./AdminDB;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: kr.co.shineware.nlp.komoran.admin.config.CustomH2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        jdbc:
          batch_size: 50
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false


files:
  default:
    basedir: defaults/    # should exist under src/main/resources
  upload:
    basedir: uploads/     # will be created under Project Root
  name:
    dicword: dic.word
    grammarin: grammar.in
    dicuser: dic.user
    fwduser: fwd.user
    irregular: dic.irregular

komoran:
  options:
    numThreads: 4

models:
  default:
    basedir: models/
    corpusdir: corpus_build/
  model:
    dir: model/

logging:
  level:
    kr.co.shineware.nlp.komoran.admin.*: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari.*: ERROR

user:
  environment: dev
  devpath: C://Users//82109//Documents//GitHub//0509//KoreaNewsCrawler//output//
#  prodpath: /apps/output/
  prodpath: /Users/skps/tmp-data/

heroku:
  connurl: jdbc:postgresql://ec2-52-49-120-150.eu-west-1.compute.amazonaws.com:5432/d7lgjb2l3i4u6b
  user: xxupjozwcgwmym
  password: 442a4b111a01b6d3d5414d845b5d06d7d4cfe29b9d8874730e9e7bf90e451b1c

#  nohup java -Xms512m -Xmx512m -Dserver.port=8000 -Dserver.address=0.0.0.0 -Duser.prodpath=/home/skps2000/apps/output/
#  -Dheroku.connurl=ec2-34-242-84-130.eu-west-1.compute.amazonaws.com:5432/d13a195br8j7nm -Dheroku.user=xxupjozwcgwmym
#  -Dheroku.password=442a4b111a01b6d3d5414d845b5d06d7d4cfe29b9d8874730e9e7bf90e451b1c
#  -jar admin-1.0.0-SNAPSHOT.jar &
